web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '/opt/docker-services/gitlab/config:/etc/gitlab'
    - '/opt/docker-services/gitlab/logs:/var/log/gitlab'
    - '/opt/docker-services/gitlab/data:/var/opt/gitlab'
